import "@styles/globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html>
      <head />
      <body>
        <Sidebar />
        <div className="content">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
